### ISSUE TITLE
Alloy project not created

### ISSUE THREAD

**Issue by ikalangita** [m1ga/titanium_with_atom#4]
Hi,

Thank you for this repo, i followed your tutorial to install alloy to atom ide but when i try to create a project  i have following error : 

`Failed to spawn command alloy. Make sure alloy is installed and on your PATH`

I just started atom, do you know how i can resolve this ?

thanks

**Comment by nuno** [comment]
@ikalangita  Close and Re-open atom editor, should work.

**Comment by m1ga** [comment]
@ikalangita are you on windows/linux/osx?

**Comment by ikalangita** [comment]
osx

2016-04-22 22:23 GMT+02:00 Michael <notifications@github.com>:

**Comment by m1ga** [comment]
have a look at this: https://github.com/m1ga/ti-create/issues/3#issuecomment-132251665
