### ISSUE TITLE
Same guide for ubuntu

### ISSUE THREAD

**Issue by tarun7singh** [m1ga/titanium_with_atom#7]
Is there any guide on the web which can help me setup this on ubuntu?

Can you guys please modify this guide for it to work on ubuntu?

**Comment by m1ga** [comment]
I'll check it with a Ubuntu VM but most of the stuff should apply for Ubuntu too. Only the `dnf` part should change

**Comment by tarun7singh** [comment]
First of all, thanks man for this fast reply.
I'm also trying the same, if I got any problem, I will mention it here.
And will it be ok if we can add ubuntu instructions too in this, so next person can find it easily?

**Comment by m1ga** [comment]
sure! In 22min my download is ready and I can adjust the tutorial 😄

**Comment by tarun7singh** [comment]
well it gave me these errors in the first step.
```
sudo apt install nodejs npm git gcc glibc.i686 glibc-devel.i686 libstdc++.i686 zlib-devel.i686 ncurses-devel.i686 libX11-devel.i686 libXrender.i686 libXrandr.i686
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package glibc.i686
E: Couldn't find any package by glob 'glibc.i686'
E: Couldn't find any package by regex 'glibc.i686'
E: Unable to locate package glibc-devel.i686
E: Couldn't find any package by glob 'glibc-devel.i686'
E: Couldn't find any package by regex 'glibc-devel.i686'
E: Unable to locate package libstdc++.i686
E: Couldn't find any package by glob 'libstdc++.i686'
E: Couldn't find any package by regex 'libstdc++.i686'
E: Unable to locate package zlib-devel.i686
E: Couldn't find any package by glob 'zlib-devel.i686'
E: Couldn't find any package by regex 'zlib-devel.i686'
E: Unable to locate package ncurses-devel.i686
E: Couldn't find any package by glob 'ncurses-devel.i686'
E: Couldn't find any package by regex 'ncurses-devel.i686'
E: Unable to locate package libX11-devel.i686
E: Couldn't find any package by glob 'libX11-devel.i686'
E: Couldn't find any package by regex 'libX11-devel.i686'
E: Unable to locate package libXrender.i686
E: Couldn't find any package by glob 'libXrender.i686'
E: Couldn't find any package by regex 'libXrender.i686'
E: Unable to locate package libXrandr.i686
E: Couldn't find any package by glob 'libXrandr.i686'
E: Couldn't find any package by regex 'libXrandr.i686'```

**Comment by m1ga** [comment]
Yes, the package names are probably different on Ubuntu. That's what I'm checking later. But googleing for the 1st package brought up: http://stackoverflow.com/a/32925911/5193915

The i686 packages are mainly for the emulator! So if you deploy to the device you shouldn't need them

**Comment by tarun7singh** [comment]
used this command 
``` 
sudo apt-get install gcc-multilib
```
and it installed lot of libraries without any errors. going to the next steps. will comment if any error encountered.

**Comment by tarun7singh** [comment]
I was able to complete the whole setup by doing some small modifications. I appreciate your help.

**Comment by m1ga** [comment]
👍 already added some Ubuntu stuff! Still installing and updating though
